import type { Context } from 'hono'
import { AppError, ErrorCode } from '@/errors'
import { listDivisionChannelsService, listDivisionValuesService, listUnmappedChannelsService, createDivisionChannelService, updateDivisionChannelService, deleteDivisionChannelService, importDivisionChannelsService, getDivisionChannelsTemplate } from './division-channels.service'
import { listDivisionChannelsQuerySchema, createDivisionChannelSchema, updateDivisionChannelSchema, divisionChannelIdParamSchema } from './division-channels.schema'
export async function handleListDivisionChannels(c: Context) { const q = await listDivisionChannelsQuerySchema.parseAsync(c.req.query()); const r = await listDivisionChannelsService(q); return c.json({ success: true, data: r }) }
export async function handleGetDivisionChannelById(c: Context) { const { id } = await divisionChannelIdParamSchema.parseAsync(c.req.param()); return c.json({ success: true, data: await listDivisionChannelsService({ company_id: 'all' as const, page: 1, limit: 20 }) }) }
export async function handleCreateDivisionChannel(c: Context) { const b = await createDivisionChannelSchema.parseAsync(await c.req.json()); const r = await createDivisionChannelService(b, c); return c.json({ success: true, data: r }, 201) }
export async function handleUpdateDivisionChannel(c: Context) { const { id } = await divisionChannelIdParamSchema.parseAsync(c.req.param()); const b = await updateDivisionChannelSchema.parseAsync(await c.req.json()); const r = await updateDivisionChannelService(id, b, c); return c.json({ success: true, data: r }) }
export async function handleDeleteDivisionChannel(c: Context) { const { id } = await divisionChannelIdParamSchema.parseAsync(c.req.param()); await deleteDivisionChannelService(id, c); return c.json({ success: true, message: 'Deleted' }) }
export async function handleImportDivisionChannels(c: Context) { const body = await c.req.parseBody(); const file = body.file instanceof File ? await body.file.arrayBuffer() : null; if (!file) throw new AppError(ErrorCode.INVALID_FILE_FORMAT, 'File wajib diisi', 400); const isXlsx = (body.file instanceof File) && body.file.type.includes('spreadsheetml'); const companyId = Number(body.company_id || 1); const r = await importDivisionChannelsService(Buffer.from(file), isXlsx, companyId, c); return c.json({ success: true, data: r }, 201) }
export async function handleGetDivisionChannelsTemplate(c: Context) { const buf = getDivisionChannelsTemplate(); return c.body(buf, 200, { 'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Content-Disposition': 'attachment; filename="division_channels_template.xlsx"' }) }
export async function handleListDivisionValues(c: Context) { const { companyId } = c.req.param(); const branchId = c.req.query('branch_id'); const r = await listDivisionValuesService(companyId === 'all' ? 'all' : Number(companyId), branchId ? Number(branchId) : undefined); return c.json({ success: true, data: r }) }
export async function handleListUnmappedChannels(c: Context) { const { companyId } = c.req.param(); const r = await listUnmappedChannelsService(companyId === 'all' ? 'all' : Number(companyId)); return c.json({ success: true, data: r }) }
