import { lazy } from 'react'

// ─── Lazy Core / Public Pages ────────────────────────────────────────────────
export const Login = lazy(() => import('../pages/Login/index'))
export const NotFound = lazy(() => import('../pages/NotFound/index'))
export const Forbidden = lazy(() => import('../pages/Forbidden/index'))
export const UnderMaintenance = lazy(() => import('../pages/UnderMaintenance/index'))

// ─── Lazy Protected Pages ────────────────────────────────────────────────────
export const Dashboard = lazy(() => import('../pages/Dashboard/index'))
export const Growth = lazy(() => import('../pages/Growth/index'))
export const Retention = lazy(() => import('../pages/Retention/index'))
export const Value = lazy(() => import('../pages/Value/index'))
// Laporan (task029.md §30.19, 2026-08-22) — tabel breakdown Growth/Retention/
// Revenue, dipisah dari halaman chart (koreksi user: "terlalu kotor jika
// chart digabung dengan tabel").
export const ReportGrowth = lazy(() => import('../pages/Report/Growth/index'))
export const ReportRetention = lazy(() => import('../pages/Report/Retention/index'))
export const ReportRevenue = lazy(() => import('../pages/Report/Revenue/index'))
export const Customers = lazy(() => import('../pages/Customers/index'))
export const CrossSelling = lazy(() => import('../pages/CrossSelling/index'))
export const CustomerMetrics = lazy(() => import('../pages/CustomerMetrics/index'))
export const DormantCustomer = lazy(() => import('../pages/DormantCustomer/index'))
export const Products = lazy(() => import('../pages/Products/index'))
export const ProductsHighMargin = lazy(() => import('../pages/ProductsHighMargin/index'))
export const ProductsTrend = lazy(() => import('../pages/ProductsTrend/index'))
export const Transactions = lazy(() => import('../pages/Transactions/index'))
export const Projects = lazy(() => import('../pages/Projects/index'))
export const Import = lazy(() => import('../pages/Import/index'))
export const Users = lazy(() => import('../pages/Users/index'))
export const RBAC = lazy(() => import('../pages/RBAC/index'))
export const Config = lazy(() => import('../pages/Config/index'))
export const AuditLog = lazy(() => import('../pages/AuditLog/index'))
export const ActivityLog = lazy(() => import('../pages/ActivityLog/index'))
export const LoginLog = lazy(() => import('../pages/LoginLog/index'))
export const Companies = lazy(() => import('../pages/Companies/index'))
export const HighMarginSettings = lazy(() => import('../pages/Settings/HighMargin/index'))
export const DivisionsSettings = lazy(() => import('../pages/Settings/Divisions/index'))
export const DivisionManagementSettings = lazy(() => import('../pages/Settings/DivisionManagement/index'))
export const CustomerIntercompanySettings = lazy(() => import('../pages/Settings/CustomerIntercompany/index'))
export const ClassificationSettings = lazy(() => import('../pages/Config/Classification/index'))
export const ThresholdSettings = lazy(() => import('../pages/Settings/Threshold/index'))
export const ParetoCustomersSettings = lazy(() => import('../pages/Settings/ParetoCustomers/index'))
export const AnalisisPage = lazy(() => import('../pages/Analisis/index'))
export const NotificationsPage = lazy(() => import('../pages/Notifications/index'))
export const AppSettings = lazy(() => import('../pages/Settings/AppSettings/index'))
export const IntegrationPage = lazy(() => import('../pages/Config/Integration/index'))
export const FeaturesPage = lazy(() => import('../pages/Config/Features/index'))
export const AbTesting = lazy(() => import('../pages/AbTesting/index'))
