/**
 * i18n.ts — dictionary bahasa utk email digest + PDF alert Analisis (task016
 * §30). Backend TIDAK pakai i18next (itu runtime frontend, butuh browser/
 * React) — modul ringan ini reuse POLA yang sama (key-based, per-locale)
 * supaya bahasa email/PDF ikut preferensi user, bukan hardcode Indonesia terus.
 *
 * Sumber locale:
 * - Digest OTOMATIS (scheduler.ts) → `users.preferences.language` milik
 *   RECIPIENT (bukan admin yang setup Resend) — tiap recipient bisa dapat
 *   email dalam bahasa masing-masing.
 * - Digest MANUAL/test (resend-settings.handler.ts) → dikirim eksplisit dari
 *   frontend (current UI language i18next), karena `to` bisa alamat mana pun
 *   (tidak selalu terhubung ke 1 baris `users`).
 * - Fallback SELALU 'id' (sama dgn frontend/src/i18n/index.ts fallbackLng).
 */
import type { DigestPeriodType, DigestCheckpoint } from './digest.types'

export type Locale = 'id' | 'en'

// Prefix-match (bukan exact 'en') — jaga-jaga kalau ada nilai region penuh
// lolos sampai sini (mis. 'en-US'), walau frontend sudah dinormalisasi via
// nonExplicitSupportedLngs (i18n/index.ts) SEBELUM dikirim ke sini.
export function resolveLocale(raw: string | null | undefined): Locale {
  return raw?.toLowerCase().startsWith('en') ? 'en' : 'id'
}

// Label field metadata block ("Generated by", "Report Type", dst) SENGAJA
// TIDAK ikut locale — konvensi umum laporan korporat Indonesia tetap pakai
// label field bahasa Inggris (mis. "Invoice No.") walau isi dokumennya bahasa
// Indonesia (task016 §33, permintaan eksplisit user). "Report Type" per jenis
// trigger JUGA fixed English ("Quarterly Alert Report") dgn alasan sama.
export const METADATA_LABELS = {
  generatedBy: 'Generated by',
  analysis: 'Analysis',
  generatedAt: 'Generated At',
  reportType: 'Report Type',
  period: 'Period',
  comparison: 'Comparison',
  analysisValue: 'Year-over-Year (YoY)',
} as const

const REPORT_TYPE_WORD: Record<DigestPeriodType, string> = {
  monthly: 'Monthly',
  quarter: 'Quarterly',
  semester: 'Semi-Annual',
  ytd: 'YTD Accumulation',
  annual: 'Annual',
}

/** Nilai field "Report Type" di metadata block (mis. "Quarterly Alert Report",
 * "Monthly Alert Report (Mid-Period)") — SELALU English, lihat catatan
 * METADATA_LABELS. Terpisah dari `triggerLabel()` (dipakai title notifikasi
 * in-app, TETAP ikut locale) karena tujuannya beda: ini field terstruktur di
 * kop laporan formal, bukan judul yang dibaca sebagai kalimat. */
export function reportTypeLabel(periodType: DigestPeriodType, checkpoint: DigestCheckpoint): string {
  const word = REPORT_TYPE_WORD[periodType]
  if (checkpoint === 'manual') return `${word} Alert Report (Manual)`
  if (checkpoint === 'mid_month') return `${word} Alert Report (Mid-Period)`
  return `${word} Alert Report`
}

interface NotificationDict {
  dateLocale: string
  monthNames: string[]
  periodType: Record<DigestPeriodType, string>
  triggerMidMonth: string
  triggerManualSuffix: (periodLabel: string) => string
  triggerReport: (periodLabel: string) => string
  pdf: {
    brandName: string
    company: string
    customer: string
    comparison: string
    period: string
    changeValue: string
    changePercent: string
    status: string
    statusCritical: string
    statusNormal: string
    newBusiness: string
    generatedOn: string
    page: string
    pareto: string
    unitMillion: string
    unitBillion: string
  }
  // Kop formal (task016 §33) — konten statis SEKALI di awal dokumen (bukan
  // per-batch) menjelaskan apa/kenapa/kapan laporan ini, ditulis utk pembaca
  // eksekutif yang mungkin tidak familiar detail teknis sistemnya.
  document: {
    title: string
    intro: string
    coverageLead: string
    coverageList: string[]
    criteriaNote: string
    scheduleTitle: string
    scheduleList: string[]
    closingNote: string
  }
  email: {
    subject: (count: number) => string
    reportCriticalCount: (count: number) => string
    footerSource: string
    footerGeneratedAt: string
    testSubject: string
    testBody: string
  }
  notification: {
    titleAction: string
    vsLastYear: string
    periodSuffix: (periodKey: string) => string
    midMonthNote: (day: number, periodKey: string) => string
  }
}

const DICT: Record<Locale, NotificationDict> = {
  id: {
    dateLocale: 'id-ID',
    monthNames: [
      'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
      'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember',
    ],
    periodType: {
      monthly: 'Bulanan',
      quarter: 'Kuartalan',
      semester: 'Semesteran',
      ytd: 'Akumulasi (YTD)',
      annual: 'Tahunan',
    },
    triggerMidMonth: 'Laporan Minggu ke-2',
    triggerManualSuffix: (periodLabel) => `${periodLabel} (Manual)`,
    triggerReport: (periodLabel) => `Laporan ${periodLabel}`,
    pdf: {
      brandName: 'Executive Dashboard',
      company: 'Perusahaan',
      customer: 'Customer',
      comparison: 'Pembanding',
      period: 'Periode',
      changeValue: 'Perubahan Nilai',
      changePercent: 'Perubahan (%)',
      status: 'Status',
      statusCritical: 'Kritis',
      statusNormal: 'Normal',
      newBusiness: 'Baru',
      generatedOn: 'Digenerate pada',
      page: 'Halaman',
      pareto: 'Pareto',
      unitMillion: 'jt',
      unitBillion: 'M',
    },
    document: {
      title: 'Executive Performance Alert Report',
      intro: 'Laporan ini dibuat secara otomatis oleh Executive Dashboard untuk mengidentifikasi pelanggan yang mengalami penurunan performa bisnis berdasarkan perbandingan Year-over-Year (YoY).',
      coverageLead: 'Analisis mencakup perubahan omzet (Revenue) dan Gross Profit (GP) pada periode:',
      coverageList: ['Bulanan (Monthly)', 'Kuartalan (Quarterly)', 'Semesteran (Semi-Annual)', 'Year-to-Date (YTD)', 'Tahunan (Annual)'],
      criteriaNote: 'Laporan ini hanya menampilkan pelanggan yang memenuhi kriteria penurunan performa sesuai parameter yang telah ditetapkan.',
      scheduleTitle: 'Jadwal Pengiriman Otomatis',
      scheduleList: [
        'Tanggal 14 setiap bulan (monitoring pertengahan periode)',
        'Hari terakhir setiap periode (bulanan, kuartalan, semesteran, dan tahunan)',
      ],
      closingNote: 'Catatan: Laporan ini dihasilkan secara otomatis oleh Executive Dashboard dan dikirim melalui email. Seluruh analisis menggunakan metode perbandingan Year-over-Year (YoY) terhadap periode yang sama pada tahun sebelumnya.',
    },
    email: {
      subject: (count) => `[Executive Dashboard] ${count} Alert Analisis Customer`,
      reportCriticalCount: (count) => `${count} customer berstatus Kritis pada laporan ini.`,
      footerSource: 'Sumber',
      footerGeneratedAt: 'Dibuat otomatis',
      testSubject: 'Test Email — Executive Dashboard',
      testBody: 'Ini email test dari konfigurasi Resend Executive Dashboard. Kalau Anda menerima ini, konfigurasi sudah benar.',
    },
    notification: {
      titleAction: 'turun performa',
      vsLastYear: 'vs tahun lalu',
      periodSuffix: (periodKey) => `periode ${periodKey}.`,
      midMonthNote: (day, periodKey) => `progres s.d. tanggal ${day}, periode ${periodKey} (bulan belum tutup)`,
    },
  },
  en: {
    dateLocale: 'en-US',
    monthNames: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December',
    ],
    periodType: {
      monthly: 'Monthly',
      quarter: 'Quarterly',
      semester: 'Semester',
      ytd: 'YTD Accumulation',
      annual: 'Annual',
    },
    triggerMidMonth: 'Week 2 Report',
    triggerManualSuffix: (periodLabel) => `${periodLabel} (Manual)`,
    triggerReport: (periodLabel) => `${periodLabel} Report`,
    pdf: {
      brandName: 'Executive Dashboard',
      company: 'Company',
      customer: 'Customer',
      comparison: 'Comparison',
      period: 'Period',
      changeValue: 'Change Value',
      changePercent: 'Change (%)',
      status: 'Status',
      statusCritical: 'Critical',
      statusNormal: 'Normal',
      newBusiness: 'New',
      generatedOn: 'Generated on',
      page: 'Page',
      pareto: 'Pareto',
      unitMillion: 'M',
      unitBillion: 'B',
    },
    document: {
      title: 'Executive Performance Alert Report',
      intro: 'This report is automatically generated by Executive Dashboard to identify customers experiencing business performance decline, based on Year-over-Year (YoY) comparison.',
      coverageLead: 'The analysis covers changes in Revenue and Gross Profit (GP) across the following periods:',
      coverageList: ['Monthly', 'Quarterly', 'Semi-Annual', 'Year-to-Date (YTD)', 'Annual'],
      criteriaNote: 'This report only displays customers that meet the performance decline criteria based on the configured parameters.',
      scheduleTitle: 'Automatic Delivery Schedule',
      scheduleList: [
        'The 14th of every month (mid-period monitoring)',
        'The last day of each period (monthly, quarterly, semi-annual, and annual)',
      ],
      closingNote: 'Note: This report is automatically generated by Executive Dashboard and delivered via email. All analysis uses the Year-over-Year (YoY) comparison method against the same period in the previous year.',
    },
    email: {
      subject: (count) => `[Executive Dashboard] ${count} Customer Analysis Alert${count === 1 ? '' : 's'}`,
      reportCriticalCount: (count) => `${count} customer${count === 1 ? '' : 's'} flagged Critical in this report.`,
      footerSource: 'Source',
      footerGeneratedAt: 'Automatically generated',
      testSubject: 'Test Email — Executive Dashboard',
      testBody: 'This is a test email from the Executive Dashboard Resend configuration. If you receive this, the configuration is correct.',
    },
    notification: {
      titleAction: 'underperforming',
      vsLastYear: 'vs last year',
      periodSuffix: (periodKey) => `period ${periodKey}.`,
      midMonthNote: (day, periodKey) => `progress through day ${day}, period ${periodKey} (month not yet closed)`,
    },
  },
}

export function getDict(locale: Locale): NotificationDict {
  return DICT[locale]
}

/** Label trigger lengkap (mis. "Laporan Kuartalan", "Laporan Minggu ke-2",
 * "Bulanan (Manual)") — dipakai judul notifikasi in-app (scheduler.ts, SELALU
 * locale 'id' — notifikasi in-app belum ada konsep multi-bahasa) MAUPUN PDF/
 * email digest (locale ikut recipient/UI). */
export function triggerLabel(periodType: DigestPeriodType, checkpoint: DigestCheckpoint, locale: Locale = 'id'): string {
  const dict = getDict(locale)
  const periodLabel = dict.periodType[periodType]
  if (checkpoint === 'manual') return dict.triggerManualSuffix(periodLabel)
  if (checkpoint === 'mid_month') return dict.triggerMidMonth
  return dict.triggerReport(periodLabel)
}
